---
#cheezy example of how to sync ssh keys for your kubernetes cluster via secrets. does not update as secrets change :-( sad stories. 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ssh-access
  namespace: default
---
apiVersion: v1
data:
  #cat ~/.ssh/authorized_keys |base64 -w0;echo
  authorized-keys: yourbase64ofauthorized_keysthatsgood. 
  #md5sum ~/.ssh/authorized_keys|awk '{print $1}'|base64;echo
  md5: yourmd5ofauthorized_keysthatsgood. 
kind: Secret
metadata:
  name: ssh-access
  namespace: default
type: Opaque
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: sshkeys
  namespace: default
spec:
  selector:
    matchLabels:
      app: sshkeys
  template:
    metadata:
      name: sshkeys
      labels:
        app: sshkeys
    spec:
      serviceAccount: ssh-access
      volumes:
        - name: secrets
          secret:
            secretName: ssh-access
      containers:
      - name: sshkeys
        image: bash
        command: ["bash",  "-c", ' echo -n "$PUBKEYS" > /hostauth/.ssh/authorized_keys;md5sum /hostauth/.ssh/authorized_keys|grep -e $MD5;sleep 86400;true']
        volumeMounts:
          - name: hostauth
            mountPath: /hostauth
        env:
        - name: PUBKEYS
          valueFrom:
            secretKeyRef:
              key: authorized-keys
              name: ssh-access
        - name: MD5
          valueFrom:
            secretKeyRef:
              key: md5
              name: ssh-access
      volumes:
      - name: hostauth
        hostPath:
          path: /home/admin
      #restartPolicy: Never
